### ISSUE TITLE
ошибка при назначении пользователя на инвентаризацию

### ISSUE THREAD

**Issue by inventreport** [oleg-barash/invent_issues#2]
При создании инвентаризации не удается назначить счетчиков.
![photo_2017-09-14_13-57-13](https://user-images.githubusercontent.com/31954915/30426477-df385d54-9954-11e7-8eea-801b05587a68.jpg)

**Comment by oleg-barash** [comment]
Пофиксил. Сейчас должно работать назначение пользователей на инвентаризацию
